name: Python Build

on: [push]  # 每次推送代码时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu系统
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4  # 设置Python环境
        with:
          python-version: '3.10'  # 使用Python 3.10

      - name: Run Python script
        run: python main.py  # 运行Python脚本
